import type { LucideIcon } from "lucide-react";
import {
  AtSign,
  Award,
  Briefcase,
  Building2,
  Code2,
  Database,
  FileSpreadsheet,
  Ghost,
  Hash,
  HelpCircle,
  Image,
  Landmark,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Music2,
  Palette,
  PenTool,
  Phone,
  Plug,
  Rocket,
  ScanLine,
  Search,
  Send,
  Star,
  Store,
  ShoppingBag,
  ShoppingCart,
  Users,
  Video,
} from "lucide-react";

export interface Integration {
  id: string;
  name: string;
  icon: LucideIcon;
}

export const INTEGRATIONS: Integration[] = [
  { id: "email", name: "Email", icon: Mail },
  { id: "linkedin", name: "LinkedIn", icon: Briefcase },
  { id: "telegram", name: "Telegram", icon: Send },
  { id: "instagram", name: "Instagram", icon: Image },
  { id: "facebook", name: "Facebook", icon: Users },
  { id: "whatsapp", name: "WhatsApp", icon: MessageCircle },
  { id: "x", name: "X (Twitter)", icon: AtSign },
  { id: "reddit", name: "Reddit", icon: MessageSquare },
  { id: "discord", name: "Discord", icon: Ghost },
  { id: "youtube", name: "YouTube", icon: Video },
  { id: "tiktok", name: "TikTok", icon: Music2 },
  { id: "googleMaps", name: "Google Maps", icon: Map },
  { id: "googleSearch", name: "Google Search", icon: Search },
  { id: "bingMaps", name: "Bing Maps", icon: Map },
  { id: "appleMaps", name: "Apple Maps", icon: MapPin },
  { id: "yelp", name: "Yelp", icon: Star },
  { id: "yellowPages", name: "Yellow Pages", icon: Phone },
  { id: "clutch", name: "Clutch", icon: Award },
  { id: "upwork", name: "Upwork", icon: Briefcase },
  { id: "fiverr", name: "Fiverr", icon: Briefcase },
  { id: "freelancer", name: "Freelancer", icon: Briefcase },
  { id: "indeed", name: "Indeed", icon: Briefcase },
  { id: "glassdoor", name: "Glassdoor", icon: Building2 },
  { id: "crunchbase", name: "Crunchbase", icon: Database },
  { id: "wellfound", name: "Wellfound (AngelList)", icon: Rocket },
  { id: "productHunt", name: "Product Hunt", icon: Rocket },
  { id: "github", name: "GitHub", icon: Code2 },
  { id: "behance", name: "Behance", icon: Palette },
  { id: "dribbble", name: "Dribbble", icon: Palette },
  { id: "pinterest", name: "Pinterest", icon: Image },
  { id: "medium", name: "Medium", icon: PenTool },
  { id: "quora", name: "Quora", icon: HelpCircle },
  { id: "threads", name: "Threads", icon: Hash },
  { id: "vk", name: "VK", icon: Users },
  { id: "odnoklassniki", name: "Odnoklassniki", icon: Users },
  { id: "avito", name: "Avito", icon: ShoppingBag },
  { id: "olx", name: "OLX", icon: ShoppingBag },
  { id: "promUa", name: "Prom.ua", icon: Store },
  { id: "rozetka", name: "Rozetka Marketplace", icon: Store },
  { id: "etsy", name: "Etsy", icon: ShoppingBag },
  { id: "amazonSellers", name: "Amazon Sellers", icon: ShoppingCart },
  { id: "shopifyStores", name: "Shopify Stores", icon: Store },
  { id: "openCorporates", name: "OpenCorporates", icon: Landmark },
  { id: "governmentRegistries", name: "Government Company Registries", icon: Landmark },
  { id: "websiteScanner", name: "Website Scanner", icon: ScanLine },
  { id: "googleBusinessProfile", name: "Google Business Profile", icon: Building2 },
  { id: "spreadsheetsAndCrm", name: "CSV / Excel / Google Sheets / Notion / CRM", icon: FileSpreadsheet },
  { id: "thirdPartyApi", name: "Third-party API Integrations", icon: Plug },
];

export const OUTREACH_HUB_MIN_PLAN = "ENTERPRISE" as const;
