export interface Language {
  code: string;
  nameEn: string;
  nameNative: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", nameEn: "English", nameNative: "English" },
  { code: "es", nameEn: "Spanish", nameNative: "Español" },
  { code: "zh", nameEn: "Chinese (Simplified)", nameNative: "中文" },
  { code: "hi", nameEn: "Hindi", nameNative: "हिन्दी" },
  { code: "ar", nameEn: "Arabic", nameNative: "العربية" },
  { code: "pt", nameEn: "Portuguese", nameNative: "Português" },
  { code: "bn", nameEn: "Bengali", nameNative: "বাংলা" },
  { code: "ru", nameEn: "Russian", nameNative: "Русский" },
  { code: "ja", nameEn: "Japanese", nameNative: "日本語" },
  { code: "de", nameEn: "German", nameNative: "Deutsch" },
  { code: "fr", nameEn: "French", nameNative: "Français" },
  { code: "ur", nameEn: "Urdu", nameNative: "اردو" },
  { code: "id", nameEn: "Indonesian", nameNative: "Bahasa Indonesia" },
  { code: "it", nameEn: "Italian", nameNative: "Italiano" },
  { code: "tr", nameEn: "Turkish", nameNative: "Türkçe" },
  { code: "ko", nameEn: "Korean", nameNative: "한국어" },
  { code: "vi", nameEn: "Vietnamese", nameNative: "Tiếng Việt" },
  { code: "uk", nameEn: "Ukrainian", nameNative: "Українська" },
  { code: "pl", nameEn: "Polish", nameNative: "Polski" },
  { code: "nl", nameEn: "Dutch", nameNative: "Nederlands" },
  { code: "th", nameEn: "Thai", nameNative: "ไทย" },
  { code: "fa", nameEn: "Persian", nameNative: "فارسی" },
  { code: "sw", nameEn: "Swahili", nameNative: "Kiswahili" },
  { code: "ro", nameEn: "Romanian", nameNative: "Română" },
  { code: "el", nameEn: "Greek", nameNative: "Ελληνικά" },
  { code: "cs", nameEn: "Czech", nameNative: "Čeština" },
  { code: "hu", nameEn: "Hungarian", nameNative: "Magyar" },
  { code: "sv", nameEn: "Swedish", nameNative: "Svenska" },
  { code: "he", nameEn: "Hebrew", nameNative: "עברית" },
  { code: "da", nameEn: "Danish", nameNative: "Dansk" },
  { code: "fi", nameEn: "Finnish", nameNative: "Suomi" },
  { code: "no", nameEn: "Norwegian", nameNative: "Norsk" },
  { code: "sk", nameEn: "Slovak", nameNative: "Slovenčina" },
  { code: "bg", nameEn: "Bulgarian", nameNative: "Български" },
  { code: "hr", nameEn: "Croatian", nameNative: "Hrvatski" },
  { code: "sr", nameEn: "Serbian", nameNative: "Српски" },
  { code: "lt", nameEn: "Lithuanian", nameNative: "Lietuvių" },
  { code: "lv", nameEn: "Latvian", nameNative: "Latviešu" },
  { code: "et", nameEn: "Estonian", nameNative: "Eesti" },
  { code: "sl", nameEn: "Slovenian", nameNative: "Slovenščina" },
  { code: "ms", nameEn: "Malay", nameNative: "Bahasa Melayu" },
  { code: "tl", nameEn: "Filipino", nameNative: "Filipino" },
  { code: "ta", nameEn: "Tamil", nameNative: "தமிழ்" },
  { code: "te", nameEn: "Telugu", nameNative: "తెలుగు" },
  { code: "mr", nameEn: "Marathi", nameNative: "मराठी" },
  { code: "gu", nameEn: "Gujarati", nameNative: "ગુજરાતી" },
  { code: "kn", nameEn: "Kannada", nameNative: "ಕನ್ನಡ" },
  { code: "ml", nameEn: "Malayalam", nameNative: "മലയാളം" },
  { code: "pa", nameEn: "Punjabi", nameNative: "ਪੰਜਾਬੀ" },
  { code: "si", nameEn: "Sinhala", nameNative: "සිංහල" },
  { code: "km", nameEn: "Khmer", nameNative: "ខ្មែរ" },
  { code: "lo", nameEn: "Lao", nameNative: "ລາວ" },
  { code: "my", nameEn: "Burmese", nameNative: "မြန်မာ" },
  { code: "ne", nameEn: "Nepali", nameNative: "नेपाली" },
  { code: "am", nameEn: "Amharic", nameNative: "አማርኛ" },
  { code: "so", nameEn: "Somali", nameNative: "Soomaali" },
  { code: "ha", nameEn: "Hausa", nameNative: "Hausa" },
  { code: "yo", nameEn: "Yoruba", nameNative: "Yorùbá" },
  { code: "ig", nameEn: "Igbo", nameNative: "Igbo" },
  { code: "zu", nameEn: "Zulu", nameNative: "isiZulu" },
  { code: "xh", nameEn: "Xhosa", nameNative: "isiXhosa" },
  { code: "af", nameEn: "Afrikaans", nameNative: "Afrikaans" },
  { code: "az", nameEn: "Azerbaijani", nameNative: "Azərbaycan" },
  { code: "ka", nameEn: "Georgian", nameNative: "ქართული" },
  { code: "hy", nameEn: "Armenian", nameNative: "Հայերեն" },
  { code: "kk", nameEn: "Kazakh", nameNative: "Қазақ тілі" },
  { code: "uz", nameEn: "Uzbek", nameNative: "Oʻzbekcha" },
  { code: "mn", nameEn: "Mongolian", nameNative: "Монгол" },
  { code: "ps", nameEn: "Pashto", nameNative: "پښتو" },
  { code: "ku", nameEn: "Kurdish", nameNative: "Kurdî" },
  { code: "sd", nameEn: "Sindhi", nameNative: "سنڌي" },
  { code: "as", nameEn: "Assamese", nameNative: "অসমীয়া" },
  { code: "or", nameEn: "Odia", nameNative: "ଓଡ଼ିଆ" },
  { code: "mai", nameEn: "Maithili", nameNative: "मैथिली" },
  { code: "sq", nameEn: "Albanian", nameNative: "Shqip" },
  { code: "mk", nameEn: "Macedonian", nameNative: "Македонски" },
  { code: "bs", nameEn: "Bosnian", nameNative: "Bosanski" },
  { code: "is", nameEn: "Icelandic", nameNative: "Íslenska" },
  { code: "ga", nameEn: "Irish", nameNative: "Gaeilge" },
  { code: "cy", nameEn: "Welsh", nameNative: "Cymraeg" },
  { code: "mt", nameEn: "Maltese", nameNative: "Malti" },
  { code: "eu", nameEn: "Basque", nameNative: "Euskara" },
  { code: "ca", nameEn: "Catalan", nameNative: "Català" },
  { code: "gl", nameEn: "Galician", nameNative: "Galego" },
  { code: "lb", nameEn: "Luxembourgish", nameNative: "Lëtzebuergesch" },
  { code: "be", nameEn: "Belarusian", nameNative: "Беларуская" },
  { code: "tg", nameEn: "Tajik", nameNative: "Тоҷикӣ" },
  { code: "tk", nameEn: "Turkmen", nameNative: "Türkmençe" },
  { code: "ky", nameEn: "Kyrgyz", nameNative: "Кыргызча" },
  { code: "yi", nameEn: "Yiddish", nameNative: "ייִדיש" },
  { code: "jv", nameEn: "Javanese", nameNative: "Basa Jawa" },
  { code: "su", nameEn: "Sundanese", nameNative: "Basa Sunda" },
  { code: "ceb", nameEn: "Cebuano", nameNative: "Cebuano" },
  { code: "haw", nameEn: "Hawaiian", nameNative: "ʻŌlelo Hawaiʻi" },
  { code: "mi", nameEn: "Maori", nameNative: "Māori" },
  { code: "sm", nameEn: "Samoan", nameNative: "Gagana Samoa" },
  { code: "st", nameEn: "Sesotho", nameNative: "Sesotho" },
  { code: "sn", nameEn: "Shona", nameNative: "chiShona" },
  { code: "rw", nameEn: "Kinyarwanda", nameNative: "Ikinyarwanda" },
  { code: "ny", nameEn: "Chichewa", nameNative: "Chichewa" },
  { code: "mg", nameEn: "Malagasy", nameNative: "Malagasy" },
  { code: "co", nameEn: "Corsican", nameNative: "Corsu" },
  { code: "fy", nameEn: "Frisian", nameNative: "Frysk" },
  { code: "hmn", nameEn: "Hmong", nameNative: "Hmoob" },
  { code: "la", nameEn: "Latin", nameNative: "Latina" },
  { code: "eo", nameEn: "Esperanto", nameNative: "Esperanto" },
];
